# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96825b7559b6953df2c2abbff1184acc45aea338727902c9d161e56f27c0493a8f34d402a4625fa852711871dd5308f4c16784617c6d3a836df237cfd2ab2663

test:
  secret_key_base: cd5ffab699d11a5facf1f24a9364d7a18ddb98243e85877b61ded37d40b2c81be2adc52411049f25721d9361b8fd01a601e4860a8b2bb302dacca8091c63ce77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
